In [35]:
import pandas as pd
import numpy as np

In [36]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns = ['cgpa','profile_score','lpa'])

In [37]:
df.head()

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

## Function to initialize the weights and bias variable

### Weights  = 0.1
### bias = 0

In [38]:
def initalize_parameters(layer_dims):

    np.random.seed(3)
    parameters = {}
    L = len(layer_dims)

    for i in range(1,L):

        parameters['W' + str(i)] = np.ones((layer_dims[i-1],layer_dims[i])) * 0.1
        parameters['b' + str(i)] = np.zeros((layer_dims[i],1))

    return parameters
        

In [42]:
initalize_parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [43]:
type(parameters)


dict

In [53]:
parameters['W1'].shape

(2, 2)

### We can have random function instead of ones and zeros in order to get random initialization

In [54]:
def linear_forward(A_prev, W,b):

    Z = np.dot(W.T, A_prev) + b

    return Z

### the above function is to calculate the output for every node

# Main function which performs Forward Propagation

In [62]:
def L_layer_forward(X, parameters):

    A = X
    L = len(parameters) // 2     # number of layers in the neural network

    for l in range(1, L+1):
        A_prev  = A
        Wl = parameters['W' + str(l)]
        bl = parameters['b' + str(l)]
        #print("A"+ str(l-1) + ": ", A_prev)
        #print("W"+str(l) + ": ",Wl)
        #print("b"+str(l) + ": ", bl)
        #print("--" * 20)

        A = linear_forward(A_prev, Wl, bl)
        #print("A"+str(l) +": ", A)
        #print("**" * 20)

    return A, A_prev

In [63]:
# Storing the first row value in X and y

X = df[['cgpa','profile_score']].values[0].reshape(2,1) # shape( np. of features, no. of training example)
y = df[['lpa']].values[0][0]


In [64]:
X

array([[8],
       [8]])

In [65]:
y

np.int64(4)

In [66]:
# Parameters Initialization

parameters = initalize_parameters([2,2,1])

L_layer_forward(X,parameters)

(array([[0.32]]),
 array([[1.6],
        [1.6]]))

In [67]:
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0])

In [68]:
# Epochs implementation

parameters = initalize_parameters([2,2,1])
epochs = 5

for i in range(epochs):

    loss = []

    for j in range(df.shape[0]):

        X = df[['cgpa','profile_score']].values[j].reshape(2,1) # Shape (number of features, number of training example)
        y = df[['lpa']].values[j][0]

        # Parameter initialization 

        y_hat, A1 = L_layer_forward(X,parameters)
        y_hat = y_hat[0][0]

        update_parameters(parameters,y,y_hat,A1,X)

        loss.append((y-y_hat)**2)

    print("Epoch - ",i+1, "Loss - ", np.array(loss).mean())

Epoch -  1 Loss -  25.321744156025517
Epoch -  2 Loss -  18.320004165722047
Epoch -  3 Loss -  9.473661050729628
Epoch -  4 Loss -  3.2520938634031613
Epoch -  5 Loss -  1.3407132589299962
